; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[common]
lib_deps_shared = 
    https://github.com/hytech-racing/HT_SCHED
    https://github.com/adafruit/Adafruit_SHARP_Memory_Display
    https://github.com/adafruit/Adafruit-GFX-Library
    Embedded Template Library@^20.39.4
    https://github.com/hytech-racing/shared_firmware_types.git


[env:genericSTM32F446RE]
check_tool = clangtidy
check_flags =
  clangtidy: --config-file=./.clang-tidy
check_severity = medium, high
test_framework=googletest
build_unflags = -std=gnu++11
build_src_filter = 
  +<*.cpp>
  -<lib/interfaces/include/lcdInterface.h>
  -<lib/interfaces/src/lcdInterface.cpp>
build_flags = 
  -std=c++17
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D USBCON
	-D USBD_VID=0x0483
	-D USBD_PID=0x0003
  -D HAL_PCD_MODULE_ENABLED
  -D HAL_CAN_MODULE_ENABLED
check_src_filters =
  +<include/*>
  +<lib/*>
  +<src/*>
monitor_speed = 115200
platform = ststm32
board = genericSTM32F446RE
framework = arduino
upload_protocol = dfu
lib_deps = 
  ${common.lib_deps_shared}
  https://github.com/pazi88/STM32_CAN.git
  https://github.com/hytech-racing/HT_CAN/releases/download/162/can_lib.tar.gz
  https://github.com/adafruit/Adafruit_NeoPixel.git

[genericSTM32H750VB]
platform = ststm32
board = genericSTM32H750VB
framework = arduino
monitor_speed = 115200
check_tool = clangtidy
check_flags =
  clangtidy: --config-file=./.clang-tidy
check_severity = medium, high
test_framework=googletest
build_unflags = -std=gnu++11
build_src_filter = 
  +<*.cpp>
  -<test_encoder.cpp>
  -<lib/interfaces/include/lcdInterface.h>
  -<lib/interfaces/src/lcdInterface.cpp>
build_flags = 
  -std=c++17
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D USBCON
	-D USBD_VID=0x0483
	-D USBD_PID=0x0003
  -D USE_HAL_DRIVER
  -D HAL_PCD_MODULE_ENABLED
  -D HAL_FDCAN_MODULE_ENABLED
  -D USBCON 
  -D USBD_USE_CDC
  -D HSE_VALUE=25000000
check_src_filters =
  +<include/*>
  +<lib/*>
  +<src/*>
lib_deps = 
  ${common.lib_deps_shared}
  https://github.com/hytech-racing/HT_CAN/releases/download/162/can_lib.tar.gz
  https://github.com/adafruit/Adafruit_NeoPixel.git
  https://github.com/gianni-carbone/STM32encoder.git
  https://github.com/MajicDesigns/MD_REncoder.git
  https://github.com/brianlow/Rotary.git
board_build.ldscript = STM32H750VB_FLASH.ld

[env:H750_dfu]
extends = genericSTM32H750VB
upload_protocol = dfu

[env:H750_stlink]
extends = genericSTM32H750VB
upload_protocol = stlink
debug_tool = stlink
debug_svd_path = svd/STM32H750x.svd
debug_speed = 24000

[env:test_encoder]
platform = ststm32
board = genericSTM32H750VB
framework = arduino
build_src_filter = 
  +<*.cpp>
  +<test_encoder.cpp>
  -<main.cpp>
  -<HT_FDCAN.cpp>
  -<Dash_Tasks.cpp>
  -<Dash_Globals.cpp>
  -<HT_SPI.cpp>
  -<SysClock_Config.h>
monitor_speed = 115200
build_flags = 
  -std=c++17
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D USBCON
	-D USBD_VID=0x0483
	-D USBD_PID=0x0003
  -D USE_HAL_DRIVER
  -D HAL_PCD_MODULE_ENABLED
  -D HAL_FDCAN_MODULE_ENABLED
  -D USBCON 
  -D USBD_USE_CDC
  -D HSE_VALUE=25000000

board_build.ldscript = STM32H750VB_FLASH.ld
lib_deps =  

  ${common.lib_deps_shared}  
  https://github.com/hytech-racing/HT_CAN/releases/download/162/can_lib.tar.gz
  https://github.com/adafruit/Adafruit_NeoPixel.git
  https://github.com/gianni-carbone/STM32encoder.git
  https://github.com/MajicDesigns/MD_REncoder.git
  https://github.com/brianlow/Rotary.git